jobs:
- job: CI
  displayName: CI
  steps:
    - bash: npm ci
      displayName: npm install

    - bash: npm audit --audit-level=moderate
      displayName: Audit Dependencies
      continueOnError: true

    - bash: npm run lint
      displayName: Lint Code

    - bash: npm run test
      displayName: Tests