jobs:
- job: Deploy
  displayName: Deploy
  variables:
  - group: aks-credentials-kv-group
  steps:
  - template: ../steps/append-sha.yaml
  - template: ../steps/debug-vars.yaml
  - template: ../steps/install-kubelogin.yaml


  - task: AzureCLI@2
    displayName: kubectl
    inputs:
      azureSubscription: $(armConnection)
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        az --version
        kubectl get pods --namespace aks-architect
      # env:
      #   IMAGE_TAG: $(imageTag)


  # Seems no access to ~ so no idea where kubeconfig is 🤷‍♀️
  # - bash: |
  #     ls -oa ~/.kube/config
  #     ls -oa $HOME/.kube/config
  #   displayName: verify location of kubeconfig

      # kubelogin convert-kubeconfig -l spn
  - bash: |
      kubelogin convert-kubeconfig -l azurecli
      kubectl get pods --namespace aks-architect
    # explicitly map Key Vault integrated secrets
    env:
      AAD_SERVICE_PRINCIPAL_CLIENT_ID:     $(aks-architect-ci-dev-sp-client-id)
      AAD_SERVICE_PRINCIPAL_CLIENT_SECRET: $(aks-architect-ci-dev-sp-client-id)
    displayName: try kubelogin
  # - bash: |
  #     cat ./k8s-manifests/deployment.yaml | envsubst | kubectl apply -f -
  #     cat ./k8s-manifests/service.yaml | envsubst | kubectl apply -f -
  #     cat ./k8s-manifests/ingress.yaml | envsubst | kubectl apply -f -
  #   env:
  #     IMAGE_TAG: $(imageTag)

  # - task: AzureCLI@2
  #   displayName: kubectl
  #   inputs:
  #     azureSubscription: $(armConnection)
  #     scriptType: bash
  #     scriptLocation: inlineScript
  #     inlineScript: |
  #       az --version
  #       kubectl get pods --namespace aks-architect
  #     env:
  #       IMAGE_TAG: $(imageTag)
