jobs:
- job: DockerPush
  displayName: Push
  steps:

  - task: Docker@2
    displayName: Docker - Login
    inputs:
      command: login
      containerRegistry: $(acrConnection)

  # So we can keep default imagePullPolicy which caches images on nodes
  - template: ../steps/append-sha.yaml
  - template: ../steps/debug-vars.yaml

  - bash: |
      docker build -t $(dockerImage):$(imageTag) .
      docker push $(dockerImage):$(imageTag)
    displayName: Docker - Build and Push

  - task: Docker@2
    displayName: Docker - Logout
    inputs:
      command: logout
      containerRegistry: $(acrConnection)

  # - task: AzureCLI@2
  #   displayName: 'ACR - lock production image'
  #   condition: eq(variables.isTag, 'True')
  #   inputs:
  #     azureSubscription: $(armConnection)
  #     scriptType: bash
  #     scriptLocation: inlineScript
  #     inlineScript: |
  #       az acr repository update \
  #         --name $(dockerRegistry) \
  #         --image $(imageName):$(imageTag) \
  #         --write-enabled false