apiVersion: v1
kind: Service
metadata:
  name: aks-architect-service
  namespace: aks-architect
spec:
  type: ClusterIP
  selector:
    app: aks-architect-nuxtjs
  ports:
  - port: 80
    targetPort: 3000
