name: $(BuildID)

schedules:
- cron: "0 0 * * *"
  displayName: Daily Midnight Build
  always: true
  branches:
    include:
    - main
    - dev
    - production

trigger:
  batch: true
  branches:
    include:
    - fix/*
    - feat/*
    - main
    - dev
  paths:
    exclude:
    - README.md

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: ci
  jobs:
  - template: jobs/ci.yaml
