name: $(BuildID)

schedules:
- cron: "0 0 * * *"
  displayName: Daily Midnight Build
  always: true
  branches:
    include:
    - main
    - dev
    - production

trigger:
  batch: true
  branches: # main, dev have own ci jobs
    include:
    - fix/*
    - feat/*
  paths:
    exclude:
    - README.md

pr:
  branches:
  - main
  - dev

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: ci
  jobs:
  - template: jobs/ci.job.yaml
