name: $(BuildID)

trigger:
  batch: true
  branches:
    include:
    - dev
  paths:
    exclude:
    - README.md

pr: none

pool:
  vmImage: 'ubuntu-latest'

variables:
- template: vars/global.vars.yaml
- template: vars/dev.vars.yaml

stages:
# - stage: ciStage
#   jobs:
#   - template: jobs/ci.yaml

- stage: buildStage
  # dependsOn: ciStage
  jobs:
  - template: jobs/docker.yaml
  - template: jobs/deploy.yaml
